# Generated by Django 5.2.17 on 2026-08-26 08:51

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pgvector must exist before any VectorField column is created,
        # including in the throwaway database the test runner builds.
        VectorExtension(),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("person", "person"), ("company", "company")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "timezone",
                    models.CharField(default="Europe/Istanbul", max_length=64),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "entities",
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("gmail", "gmail"),
                            ("gcal", "gcal"),
                            ("shopify", "shopify"),
                            ("meta_ads", "meta_ads"),
                            ("telegram", "telegram"),
                            ("rss", "rss"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credentials_enc", models.BinaryField(blank=True, null=True)),
                ("sync_cursor", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("reauth_required", "reauth_required"),
                            ("disabled", "disabled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("public_key", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=300)),
                (
                    "trust_level",
                    models.CharField(
                        choices=[
                            ("self", "self"),
                            ("trusted", "trusted"),
                            ("known", "known"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_identities",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "agent identities",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("dedup_key", models.CharField(max_length=200)),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField()),
                ("processed", models.BooleanField(default=False)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.entity",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.datasource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExplorationLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "lane",
                    models.CharField(
                        choices=[
                            ("exploit", "exploit"),
                            ("adjacent", "adjacent"),
                            ("counter", "counter"),
                            ("random", "random"),
                        ],
                        max_length=20,
                    ),
                ),
                ("items_served", models.IntegerField(default=0)),
                ("feedback_up", models.IntegerField(default=0)),
                ("feedback_down", models.IntegerField(default=0)),
                ("promoted", models.IntegerField(default=0)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exploration_ledger",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExposureItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sector", "sector"),
                            ("currency", "currency"),
                            ("supplier", "supplier"),
                            ("asset", "asset"),
                            ("customer_segment", "customer_segment"),
                            ("obligation", "obligation"),
                            ("location", "location"),
                            ("skill", "skill"),
                        ],
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("weight", models.FloatField(default=1.0)),
                (
                    "source",
                    models.CharField(
                        choices=[("user", "user"), ("derived", "derived")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposures",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("briefing_item", "briefing_item"),
                            ("draft", "draft"),
                            ("finding", "finding"),
                            ("exploration", "exploration"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_ref", models.CharField(max_length=200)),
                (
                    "signal",
                    models.CharField(
                        choices=[("up", "up"), ("down", "down"), ("edited", "edited")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterestNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("strength", models.FloatField(default=0.5)),
                (
                    "origin_lane",
                    models.CharField(
                        choices=[
                            ("exploit", "exploit"),
                            ("adjacent", "adjacent"),
                            ("counter", "counter"),
                            ("random", "random"),
                        ],
                        default="exploit",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLMUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("tier", models.CharField(max_length=20)),
                ("purpose", models.CharField(max_length=100)),
                ("input_tokens", models.BigIntegerField(default=0)),
                ("output_tokens", models.BigIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_usage",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("episodic", "episodic"),
                            ("semantic", "semantic"),
                            ("relationship", "relationship"),
                            ("goal", "goal"),
                            ("identity", "identity"),
                            ("exposure", "exposure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                ("provenance", models.CharField(max_length=200)),
                ("confidence", models.FloatField()),
                (
                    "origin_lane",
                    models.CharField(
                        choices=[
                            ("exploit", "exploit"),
                            ("adjacent", "adjacent"),
                            ("counter", "counter"),
                            ("random", "random"),
                        ],
                        default="exploit",
                        max_length=20,
                    ),
                ),
                ("decay_exempt_until", models.DateTimeField(blank=True, null=True)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="core.entity",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.event",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="core.memoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeshConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("purpose", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("agreed", "agreed"),
                            ("declined", "declined"),
                            ("awaiting_approval", "awaiting_approval"),
                            ("closed", "closed"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="core.entity",
                    ),
                ),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="core.agentidentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeshMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "in"), ("out", "out")], max_length=10
                    ),
                ),
                ("kind", models.CharField(max_length=50)),
                ("body", models.JSONField()),
                ("redaction_note", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.meshconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["conversation_id", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposedAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=50)),
                ("action_type", models.CharField(max_length=100)),
                ("dedup_key", models.CharField(max_length=200)),
                ("payload", models.JSONField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("edited", "edited"),
                            ("rejected", "rejected"),
                            ("executed", "executed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="core.entity",
                    ),
                ),
                (
                    "origin_conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.meshconversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=300)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.entity",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proposedaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal", models.TextField()),
                (
                    "lane",
                    models.CharField(
                        choices=[
                            ("exploit", "exploit"),
                            ("adjacent", "adjacent"),
                            ("counter", "counter"),
                            ("random", "random"),
                        ],
                        default="exploit",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("done", "done"),
                            ("capped", "capped"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("step_budget", models.IntegerField(default=8)),
                ("token_budget", models.IntegerField(default=40000)),
                ("steps_used", models.IntegerField(default=0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_tasks",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("tool", models.CharField(max_length=50)),
                ("tool_input", models.JSONField(blank=True, default=dict)),
                ("result_ref", models.CharField(blank=True, max_length=200)),
                ("tokens", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.researchtask",
                    ),
                ),
            ],
            options={
                "ordering": ["task_id", "index"],
            },
        ),
        migrations.CreateModel(
            name="ShareContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allowed_fields", models.JSONField(blank=True, default=list)),
                ("purpose", models.CharField(max_length=200)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_user_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_contracts",
                        to="core.entity",
                    ),
                ),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="core.agentidentity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meshconversation",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sharecontract",
            ),
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("text", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImpactFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim", models.TextField()),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("risk", "risk"),
                            ("opportunity", "opportunity"),
                            ("neutral", "neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "magnitude",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="core.entity",
                    ),
                ),
                (
                    "exposure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="core.exposureitem",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.researchtask",
                    ),
                ),
                (
                    "evidence",
                    models.ManyToManyField(
                        related_name="findings", to="core.sourcedocument"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("position", models.TextField()),
                ("confidence", models.FloatField(default=0.5)),
                ("last_challenged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stances",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Briefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sections", models.JSONField(blank=True, default=list)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefings",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "date"), name="uniq_briefing_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=100)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("suggest", "suggest"),
                            ("draft", "draft"),
                            ("auto_candidate", "auto_candidate"),
                            ("auto", "auto"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("window_stats", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "action policies",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "action_type"), name="uniq_action_policy"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "owner"), ("member", "member")],
                        default="owner",
                        max_length=20,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.entity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "user"), name="uniq_entity_member"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["entity", "processed", "occurred_at"],
                name="core_event_entity__ab33d2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("entity", "type", "dedup_key"), name="uniq_event_dedup"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("dedup_key", ""), _negated=True),
                name="event_dedup_key_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="explorationledger",
            constraint=models.UniqueConstraint(
                fields=("entity", "date", "lane"), name="uniq_explore_ledger"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedbacksignal",
            constraint=models.UniqueConstraint(
                fields=("entity", "target_type", "target_ref"), name="uniq_feedback"
            ),
        ),
        migrations.AddIndex(
            model_name="llmusage",
            index=models.Index(
                fields=["entity", "date"], name="core_llmusa_entity__ae9801_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="llmusage",
            constraint=models.UniqueConstraint(
                fields=("entity", "date", "tier", "purpose"), name="uniq_llm_usage"
            ),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["entity", "kind", "valid_until"],
                name="core_memory_entity__93145e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("provenance", ""), _negated=True),
                name="memory_provenance_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                name="memory_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposedaction",
            constraint=models.UniqueConstraint(
                fields=("entity", "action_type", "dedup_key"), name="uniq_action_dedup"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposedaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("dedup_key", ""), _negated=True),
                name="action_dedup_key_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchstep",
            constraint=models.UniqueConstraint(
                fields=("task", "index"), name="uniq_research_step_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.UniqueConstraint(
                fields=("entity", "content_hash"), name="uniq_sourcedoc"
            ),
        ),
        migrations.AddConstraint(
            model_name="impactfinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("claim", ""), _negated=True),
                name="finding_claim_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="impactfinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                name="finding_confidence_range",
            ),
        ),
    ]
