# Generated by Django 5.2.17 on 2026-08-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="calls",
            field=models.IntegerField(default=0),
        ),
    ]
